title : Wall-E - From Space From Earth
description: '用心设计未来'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
gems: [jekyll-paginate]
permalink: /:year/:month/:title.html
# excerpt_separator: '<!-- more -->'
